# Generated by Django 2.2.16 on 2022-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220504_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None, verbose_name='Рейтинг'),
        ),
    ]
